mode: "debug"
app_name: "Website"
key: "1234"
gql_playground_key: "1234"
ssl: false
recpatcha_private_key : "6LdG5nsUAAAAAIHmXB0mejGdAT2YAscC3PmgiNmr"

server:
  port: 7001

database:
  host: "localhost"
  name: "jeogacom_mangodb"
  password: "root"
  port: "5432"
  type: "postgres"
  user: "postgres"
  sslmode: "disable"